### ISSUE TITLE
Proguard Rules for plugin

### ISSUE THREAD

**Issue by t4tapas** [martinkasa/capacitor-secure-storage-plugin#39]
This plugin is getting the following error when `minifyEnabled` is set to `true` in Android. 

```
E/Capacitor: Unable to read file at path public/plugins
E/Capacitor/Plugin: Item with given key does not exist
    java.lang.Exception: Item with given key does not exist
        at com.whitestein.securestorage.SecureStoragePlugin.Z(:95)
        at com.whitestein.securestorage.SecureStoragePlugin.get(:45)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.t0.h(:121)
        at com.getcapacitor.a0.D(:584)
        at com.getcapacitor.a0.E(Unknown Source:0)
        at com.getcapacitor.a.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.os.HandlerThread.run(HandlerThread.java:67)
E/GmsClient: unable to connect to service: com.google.android.gms.leibniz.events.service.START on com.google.android.gms
```

Could you please share the ProGuard rule for this plugin which is needed for `proguard-rules.pro` file?

**Comment by martinkasa** [comment]
@t4tapas can you try it with the most recent version? I rebased the plugin with latest plugin template from Ionic, maybe they fixed it. I do not use ProGuard, so I can not tell.

**Comment by Saqib92** [comment]
> @t4tapas can you try it with the most recent version? I rebased the plugin with latest plugin template from Ionic, maybe they fixed it. I do not use ProGuard, so I can not tell.

Still happening on latest plugin `v0.8.1`.

**Comment by rgbaman** [comment]
Got the same issue here using the latest `npm`. Even catching the error with a console log breaks the entire app.

**Comment by wellwoller** [comment]
Is there any advancement on this issue?

**Comment by NillDk** [comment]
Another interesting finding.

We have 2 values in our storage: 
- OldKey (has been there for a while - this one throws `javax.crypto.IllegalBlockSizeException` when reading it)
- NewKey (recently added - this one works fine)

Case 1:
We uninstall + reinstall the App, the OldKey persists and NewKey is gone.

Case 2:
We call `SecureStoragePlugin.clear()` both keys/values are gone.
We the kill the App and reopen it, both keys/values are still gone.
However, if we then uninstall + reinstall the App.
The OldKey reappears.

Case 3:
The value of OldKey is 'AAA' (the one that throws).
We call `SecureStoragePlugin.set({ OldKey, 'BBB'})`
We uninstall + reinstall the App.
The value of OldKey is now 'AAA' (expected to be completely gone due to the uninstall/reinstall).

@martinkasa do you have any idea on what's going on here?
Could the KeyStore be distributed to some external storage and read from there?
Or do you have any other suggestions to, why the old value reappears?

Would you be interested in a screen sharing / remote debug session?

**Comment by alexcroox** [comment]
This issue still exists in the latest version. The only work around is to get the key first, which does correctly throw:

```
try {
        await this.$native.secureStorage.get({ key: 'accessToken' })
        
        // This cannot be caught so we need to check above first
        this.$native.secureStorage.remove({ key: 'accessToken' })
      } catch (error) {
        // STUB
      }
```

**Comment by GuillaumeUnice** [comment]
Is there any enhancement here?

@alexcroox I don't get your point could explain to me?

I have the impression when we send multiple get in parallel there is an asynchronous issue otherwise seems to work.

**Comment by alexcroox** [comment]
@GuillaumeUnice previously I had `.remove` in a try/catch in case the key didn't exist. But .remove doesn't throw an exception so I couldn't catch it.

However `.get` does throw an exception, so you have to do .get first before .remove to avoid errors bubbling that you can't catch.

**Comment by GuillaumeUnice** [comment]
Ok just to sum up the problem because everything as diverged from the initial issue.
The problem is related to the use of `.get` which throw `item with given key does not exist` when the key doesn't exist whereas the error should be on the catch of the `.get` promise because here we can't handle it and manage it at all (currently the throw is on the capacitor internal callback system).

The only solution to handle it for now is to use other method for instances use `.keys` to check before calling `.get` but it's kinda workaround so whether someone can handle the `.get` error more properly it will be more suitable in use.

**Comment by RichardScholtenAareonNL** [comment]
We are running in to the same problem where an error is thrown if a key does not exist. 

We do not call the methods like getItem setItem by ourselves, we pass the securestorage to a 3rd party package with the Storage interface. The external package stops working whenever an error is thrown, this is not in our control. 

Throwing an error if a key does not exist is not compliant with the specs: https://html.spec.whatwg.org/multipage/webstorage.html#dom-storage-getitem

**Comment by Artkoch** [comment]
I'm having the same issue, is there a solution?
