### ISSUE TITLE
Silently crash when storing string with more than 256 bytes

### ISSUE THREAD

**Issue by Rajarml** [martinkasa/capacitor-secure-storage-plugin#4]
Trying to store (encryptedly) a long string (for instance a JWT token of 2075 chars).

When debugging the process, the issue lies in the "encrypt" function of  PasswordStorageHelper_SDK18 class.

```
javax.crypto.IllegalBlockSizeException: input must be under 256 bytes
        at com.android.org.conscrypt.OpenSSLCipherRSA.engineDoFinal(OpenSSLCipherRSA.java:299)
        at javax.crypto.Cipher.doFinal(Cipher.java:2055)
        at com.whitestein.securestorage.PasswordStorageHelper$PasswordStorageHelper_SDK18.encrypt(PasswordStorageHelper.java:313)
        at com.whitestein.securestorage.PasswordStorageHelper$PasswordStorageHelper_SDK18.setData(PasswordStorageHelper.java:254)
        at com.whitestein.securestorage.PasswordStorageHelper.setData(PasswordStorageHelper.java:70)
        at com.whitestein.securestorage.SecureStoragePlugin.set(SecureStoragePlugin.java:27)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
        at com.getcapacitor.Bridge$2.run(Bridge.java:526)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

A work around from the web side, could be splitting the long string into smaller one (245bytes in fact) but this should not be necessary!

**Comment by Rajarml** [comment]
After some search, additional info: https://crazytechstuffz.blogspot.com/2015/08/rsa-encryptiondecryption-for-longer.html

**Comment by Rajarml** [comment]
Does the maintainer @martinkasa  still here?

**Comment by martinkasa** [comment]
Hi, thanks for reporting issue, I will look at it asap.

**Comment by martinkasa** [comment]
@Rajarml  please test release 0.3.0 and let me know if it works.

**Comment by martinkasa** [comment]
Closing the issue. @Rajarml if you have still problem with saving long values, I will reopen it.

**Comment by Rajarml** [comment]
In fact I've done what was needed for splitting the long string into 245 max bytes chunks from the angular side, then I encrypt those chunks, I store the needed sorted keys in the localStorage. And do the reverse for the decryption :)
I'm on something else so I don't know if I could test it again
