### ISSUE TITLE
No available storage method found

### ISSUE THREAD

**Issue by RHinderiks** [martinkasa/capacitor-secure-storage-plugin#71]
Upgrading to the latest capacitor (v4) it looks like this plugin is no longer working. We get the following errors

`11-30 10:02:26.059 E/Capacitor/Console(29244): File: http://localhost/vendor.js - Line 15075 - Msg: ERROR Error: Uncaught (in promise): Error: No available storage method found.
11-30 10:02:26.059 E/Capacitor/Console(29244): Error: No available storage method found.
11-30 10:02:26.059 E/Capacitor/Console(29244):     at http://localhost/vendor.js:94851:25
11-30 10:02:26.059 E/Capacitor/Console(29244):     at push.99140._ZoneDelegate.invoke (http://localhost/polyfills.js:422:30)
11-30 10:02:26.059 E/Capacitor/Console(29244):     at http://localhost/polyfills.js:1339:38
11-30 10:02:26.059 E/Capacitor/Console(29244):     at push.99140._ZoneDelegate.invokeTask (http://localhost/polyfills.js:456:35)
11-30 10:02:26.059 E/Capacitor/Console(29244):     at Object.onInvokeTask (http://localhost/vendor.js:37288:33)
11-30 10:02:26.059 E/Capacitor/Console(29244):     at push.99140._ZoneDelegate.invokeTask (http://localhost/polyfills.js:455:64)
11-30 10:02:26.059 E/Capacitor/Console(29244):     at push.99140.Zone.runTask (http://localhost/polyfills.js:227:51)
11-30 10:02:26.060 E/Capacitor/Console(29244): File: http://localhost/vendor.js - Line 88712 - Msg: Cache initialization error:  Error: No available storage method found.`

**Comment by tafelnl** [comment]
I upgraded to Capacitor v4 and `v0.8.1` of this plugin, but didn't encounter issues. However because of your comment I'm hesitating to release it to production. Are you still encountering issues in combination with Capacitor v4?

**Comment by tafelnl** [comment]
Next to the already suggested https://github.com/evgenyneu/keychain-swift, there exist a few other alternatives:

- https://github.com/kishikawakatsumi/KeychainAccess
- https://github.com/square/Valet

**Comment by martinkasa** [comment]
this seems to be capacitor v4 related. and most probably was fixed with next releases.
